### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by michael-brennan2005** [fairviewrobotics/2022-robot-code#10]
- [ ] tank drive command: add trapezoid profiling, cubed speeds
- [ ] second drive system: joystick to point towards angle, trigger to control speed
- [ ] third drive system: direct drive, joystick -> motor speeds
